# Generated by Django 5.2.8 on 2025-11-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercisereport',
            old_name='angles_data',
            new_name='motion_data',
        ),
        migrations.AddField(
            model_name='exercisereport',
            name='deviation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercisereport',
            name='max_angle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercisereport',
            name='normal_angle',
            field=models.FloatField(default=135),
        ),
        migrations.AddField(
            model_name='exercisereport',
            name='performance_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='exercisereport',
            name='duration_seconds',
            field=models.FloatField(default=0),
        ),
    ]
