# Generated by Django 5.2.8 on 2025-11-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_rename_angles_data_exercisereport_motion_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisereport',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercisereport',
            name='performance_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exercisereport',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
